In [8]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg 

m = np.array([[9,8,-2,2,-2],
              [7,-3,-2,7,2],
              [2,-2,2,-7,6],
              [4,8,-3,3,-1],
              [2,2,-1,1,4]])


print(m)

if all(len(row) == len(m) for row in m):
    print("Rozpatrywana macierz jest kwadratowa")
    print()

    n = len(m)
    u = ([[0]*n for x in range (n)])
    l = ([[0]*n for x in range (n)])
    
    for ii in range (n):
        u[ii][ii] = 1
        #L[ii][ii] = 1
        for kk in range (ii, n):
            suma  = sum([u[jj][kk]*l[ii][jj] for jj in range(ii)])
            u[ii][kk] = m[ii][kk] - suma
            
        for kk in range(ii, n):
            if ii == kk:
                l[ii][ii] = 1
                continue
            suma = sum([l[kk][jj]*u[jj][ii] for jj in range(ii)])
            l[kk][ii] = (m[kk][ii] -suma)/u[ii][ii]
    
    print("Macierz dolna:")
    print()
    print(np.array(l))
    print()
    print("Macierz gorna:")
    print()
    print(np.array(u))
    print()
    print("Wyniki pochodzacy z wbudowanej funkcji:")
    print()
    
    m_lu =scipy.linalg.lu(m)
    

    print(np.array(m_lu))

else:
    (print("Rozpatrywana macierz nie jest kwadratowa"))


[[ 9  8 -2  2 -2]
 [ 7 -3 -2  7  2]
 [ 2 -2  2 -7  6]
 [ 4  8 -3  3 -1]
 [ 2  2 -1  1  4]]
Rozpatrywana macierz jest kwadratowa

Macierz dolna:

[[ 1.          0.          0.          0.          0.        ]
 [ 0.77777778  1.          0.          0.          0.        ]
 [ 0.22222222  0.40963855  1.          0.          0.        ]
 [ 0.44444444 -0.48192771 -0.8853211   1.          0.        ]
 [ 0.22222222 -0.02409639 -0.21559633  0.36526946  1.        ]]

Macierz gorna:

[[ 9.          8.         -2.          2.         -2.        ]
 [ 0.         -9.22222222 -0.44444444  5.44444444  3.55555556]
 [ 0.          0.          2.62650602 -9.6746988   4.98795181]
 [ 0.          0.          0.         -3.83027523  6.01834862]
 [ 0.          0.          0.          0.          3.40718563]]

Wyniki pochodzacy z wbudowanej funkcji:


[[[ 1.          0.          0.          0.          0.        ]
  [ 0.          1.          0.          0.          0.        ]
  [ 0.          0.          1.     